version: 0.2 
phases: 
    install: 
        runtime-versions: 
            nodejs: 10 
        commands: 
            - npm install -g typescript 
            - npm install 
    pre_build: 
        commands: 
            - echo prebuild phase
            - aws codeartifact login --tool npm --repository sample-nodejs --domain nodejs --domain-owner 501810742264
    build: 
        commands: 
            - echo Build started on `date` 
#           - npm run build 
#            - npm start
#            - npm test 
    post_build: 
        commands: 
            - echo Build completed on `date` 
            - npm publish
cache: 
    paths: 
        - 'node_modules/**/*' 
artifacts: 
    files: 
        - '**/*' 
    name: yourBuildName-$(date +%Y-%m-%d)